//! Built-in starter catalog. Built-ins are ordinary manifest+bundle pairs
//! run through the exact same decode/verify path as synced apps — "Built
//! into Riot" is a provenance label, not a trust shortcut, and a built-in
//! still needs an organizer's per-space trust decision to launch.
//!
//! The catalog is empty until the WebView runtime lands (nothing could
//! launch a built-in yet); the checklist app's pair arrives with that
//! follow-up, generated by `riot-app pack` and committed under
//! `fixtures/apps/`.
//!
//! Starter integrity is content-addressed, not signature-verified: there
//! are no committed private keys for built-in apps, only a fixed committed
//! public `AuthorIdentity` in each shipped manifest.

use super::bundle::decode_app_bundle;
use super::directory::{AppProvenance, IndexedApp};
use super::index::app_bundle_digest;
use super::manifest::{app_id_for, decode_manifest};

/// (manifest_bytes, bundle_bytes) pairs embedded at compile time.
pub const STARTER_CATALOG: &[(&[u8], &[u8])] = &[];

/// Decodes and integrity-checks every pair; invalid pairs are silently
/// excluded, mirroring the import path's treatment of invalid items.
pub fn verify_starter_catalog(pairs: &[(&[u8], &[u8])]) -> Vec<IndexedApp> {
    pairs
        .iter()
        .filter_map(|(manifest_bytes, bundle_bytes)| {
            let manifest = decode_manifest(manifest_bytes).ok()?;
            let bundle = decode_app_bundle(bundle_bytes).ok()?;
            if manifest.entry_point != bundle.entry_point {
                return None;
            }
            let app_id = app_id_for(&manifest, &app_bundle_digest(bundle_bytes)).ok()?;
            Some(IndexedApp {
                app_id,
                manifest,
                bundle_present: true,
                provenance: AppProvenance::BuiltIn,
                manifest_timestamp_micros: 0,
            })
        })
        .collect()
}
