//! Which namespaces a communal author can be minted into, and which cannot.
//!
//! Willow encodes the *kind* of a namespace in the id itself: communal ids have
//! an even final byte, owned ids do not. That is the whole of the rule, and it
//! is load-bearing — a communal namespace has no owner, so any peer may mint a
//! subspace key inside it, which is exactly what joining a space does. An owned
//! namespace has a root secret, and minting an author into it without that
//! secret would produce entries nobody can authorise.
//!
//! So the refusal below is not a validation nicety. It is the line between a
//! space you can join and one you cannot.

use riot_core::willow::{
    generate_communal_author, generate_communal_author_for_namespace,
    generate_communal_author_with, generate_space_organizer_author, OsEntropy, OwnedRoot,
    WillowError,
};

/// An owned namespace cannot host a communal author, and says so specifically —
/// `NamespaceNotCommunal`, not a generic failure — because the caller's remedy
/// (this is not a space you can join) depends on knowing which it was.
#[test]
fn an_owned_namespace_cannot_host_a_communal_author() {
    // The rule, stated directly: an odd final byte is an owned-shaped id.
    let mut owned_shaped = [0_u8; 32];
    owned_shaped[31] = 1;
    assert!(
        matches!(
            generate_communal_author_for_namespace(owned_shaped),
            Err(WillowError::NamespaceNotCommunal)
        ),
        "an owned-shaped namespace id was accepted as communal"
    );

    // And the same rule applied to a real owned namespace, generated by the
    // owned-root constructor rather than hand-shaped here.
    let owned = OwnedRoot::generate().expect("owned root");
    let namespace_id = *owned.namespace_id().as_bytes();
    assert!(
        matches!(
            generate_communal_author_for_namespace(namespace_id),
            Err(WillowError::NamespaceNotCommunal)
        ),
        "a real owned namespace was accepted as communal"
    );
}

/// A communal namespace admits a fresh author, and that author is genuinely
/// *inside* the namespace it joined while carrying a signing key of its own.
/// Both halves matter: the first is what lets someone write into a space they
/// did not create, the second is what stops them writing as anybody else.
#[test]
fn a_communal_namespace_admits_a_fresh_author_with_its_own_key() {
    let creator = generate_communal_author().expect("author");
    let namespace_id = creator.identity().namespace_id;

    let joiner =
        generate_communal_author_for_namespace(namespace_id).expect("a communal namespace is join");

    assert_eq!(
        joiner.identity().namespace_id,
        namespace_id,
        "the joiner must land inside the namespace it joined"
    );
    assert_ne!(
        joiner.identity().signing_key_id,
        creator.identity().signing_key_id,
        "the joiner must sign with its own key, never the creator's"
    );

    // Two joiners of the same space are distinct people.
    let second = generate_communal_author_for_namespace(namespace_id).expect("second joiner");
    assert_ne!(
        second.identity().signing_key_id,
        joiner.identity().signing_key_id
    );
}

/// A space organizer's namespace *is* its own subspace key, which is what makes
/// the organizer derivable by every member from the space id alone. It is still
/// a communal namespace — the organizer gets no Willow-level privilege from it.
#[test]
fn a_space_organizers_namespace_is_its_own_subspace_key_and_still_communal() {
    let organizer = generate_space_organizer_author().expect("organizer");
    let identity = organizer.identity();
    assert_eq!(
        identity.namespace_id, identity.signing_key_id,
        "an organizer's namespace is its own subspace key"
    );

    // Still communal: anyone may mint an author inside it, which is how members
    // join the organizer's space at all.
    let member = generate_communal_author_for_namespace(identity.namespace_id)
        .expect("a member can join an organizer's space");
    assert_eq!(member.identity().namespace_id, identity.namespace_id);
    assert_ne!(member.identity().signing_key_id, identity.signing_key_id);
}

/// The injectable-entropy constructor is the one the conformance suite drives,
/// and it must produce exactly what the OS constructor produces: an author in a
/// communal namespace. A test-only constructor that could mint a non-communal
/// author would be testing a system we do not ship.
#[test]
fn the_injectable_entropy_constructor_produces_a_communal_author() {
    let author = generate_communal_author_with(&mut OsEntropy).expect("author");
    let namespace_id = author.identity().namespace_id;

    // The namespace it chose is communal — proven by the fact that another
    // author can be minted into it.
    generate_communal_author_for_namespace(namespace_id)
        .expect("the namespace it produced must be communal");

    // And it is a fresh identity each time, not a fixed test vector.
    let second = generate_communal_author_with(&mut OsEntropy).expect("author");
    assert_ne!(
        second.identity().signing_key_id,
        author.identity().signing_key_id
    );
}
